export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_AVATAR_UPLOAD = 'ACCOUNT_AVATAR_UPLOAD';
export const ACCOUNT_EDIT_USER = 'ACCOUNT_EDIT_USER';